
sdk_path: /home/freezellov/Android/Sdk
repo_keyalias: eldos123
keystore: keystore.p12
keystorepass: j4egh4XFStxvlQoD2lzI7gJfDZb0wIUdoKLtSGeoDFY=
keypass: j4egh4XFStxvlQoD2lzI7gJfDZb0wIUdoKLtSGeoDFY=
keydname: CN=eldos123, OU=F-Droid
repo_name: "GoreDroid repo"
repo_description: "репозиторий от пидораса страны"
repo_url: "https://freezellov.github.io/goredroid-repo/repo"


